Create function run_checkLPC
carrien/free-speech pull request #69
Opened 2022-11-21 17:43 UTC by cwnaber

This function can be called in contexts where the experiment-programmer wants to collect information about a participant's LPC order or default vowel space area in a pretest phase. It adds a few features not previously used in other experiments:
* Asks the experimenter to verify that the recorded sample was good, rather than assuming it was good and moving on
* Verifies that a file `nlpc.mat` was actually saved. (It might not be saved if the experimenter chooses "Exit without saving" from within the check_audapterLPC GUI.) If no file was saved, this function re-collects speech samples.

Other pull requests in the repos current-studies and cerebellar-battery depend on this pull request. They should be merged at the same time.

2022-11-21 18:19 UTC, carrien commented
Thanks, Chris. I want to be careful about how different defaults interact with each other; it's not clear to me why we set defaults inside this function and also with set_exptDefaults(exptPre). Can we just do the latter?

2022-11-21 18:34 UTC, cwnaber commented
The default parameters set here are different than each of the default parameters in `set_exptDefaults`. This function is specifically for the purpose of running the LPC check pretest phase. I set these defaults based on what the majority of functions were previously using as their settings during the LPC check pretest phase.

To your suggestion, it's possible that we could change the values in set_exptDefaults to try to better align with what we want during the LPC check pretest phase. But it's not clear to me that on a conceptual level that's what we want the values in set_exptDefaults to be determined by. Also, I wouldn't feel comfortable changing the values in set_exptDefaults without doing a fair amount of research, since it's used so extensively.

2023-05-24 13:38 UTC, cwnaber commented
@carrien I integrated your comments, and this is ready for re-review.

2023-05-27 03:40 UTC, carrien requested changes

2023-05-27 03:40 UTC, carrien commented on experiment_helpers/run_checkLPC.m
> +defaultParams.breakTrials = exptPre.ntrials; % no breaks
Has this been tested without specifying exptPre as an input arg? It looks like that would produce an error here, as it would be blank.

2023-05-27 03:40 UTC, carrien commented on experiment_helpers/run_checkLPC.m
> +    exptPre = [];
```suggestion
    exptPre = struct;
```

2023-05-30 23:08 UTC, closed without merging

2023-05-30 23:08 UTC, cwnaber commented
Replaced by #94