Update RMS monitor figure
carrien/free-speech pull request #92
Opened 2023-05-23 21:58 UTC by cwnaber

Example images using "pretest" defaults and "main" defaults, respectively.

![image](https://github.com/carrien/free-speech/assets/50926971/6ee669ef-7ba6-490a-b055-39d01c4a4d34)

![image](https://github.com/carrien/free-speech/assets/50926971/82bff7c2-1756-44f9-a7a5-e955892a5a8d)

2023-05-24 17:18 UTC, carrien requested changes

2023-05-24 17:18 UTC, carrien commented on experiment_helpers/check_rmsThresh.m
> +            end
This is OK for today but I'd like to rework this so the rms calculation is not happening inside this `isgraphics` if statement. Only the plotting should happen in here. I'd suggest moving lines 63-89 before the isgraphics if statement, and replacing line 65 with something like:
```
[rmsValue,onset] = max(data.rms(:,1));
offset = offset;
```
or alternatively
```
rmsValue = max(data.rms(:,1));
onset = NaN;
offset = NaN;
```
Then you can end the switch/case. Afterwards, inside the isgraphics if statement, you can call the same plotting lines regardless of which case we're in.

2023-05-24 17:18 UTC, carrien commented on experiment_helpers/check_rmsThresh.m
> +    end
Similar to above; I don't think bGoodTrial should be set inside this isgraphics if statement. We should set it first, then plotting is separate. It doesn't change functionality so I'm okay making this adjustment later.

2023-05-24 17:18 UTC, carrien commented on experiment_helpers/set_exptDefaults.m
> +%% amplitude tracking parameters - old, mostly used with brut
We should be using these in a lot of experiments with noise masking, so I would not add this comment.

2023-05-24 17:18 UTC, carrien commented on experiment_helpers/set_exptDefaults.m
> +
Can we just add these fields to amplcalc instead of creating "amp"?

2023-05-26 17:56 UTC, cwnaber commented
@carrien More revisions to address your comments. Individual commits for each situation, though the diff'er had some trouble with the reorganizing commit. Let me know if this is what you had in mind.

2023-05-26 17:58 UTC, cwnaber commented
In `check_rmsThresh`, using `params.checkMode = 'peak'` now plots a magenta circle on the axis at the peak.

![image](https://github.com/carrien/free-speech/assets/50926971/34feb1d5-ca0e-476f-a027-32f49998eac4)

2023-05-30 17:09 UTC, carrien approved these changes

2023-05-30 18:09 UTC, merged